[build]
  # No build command needed for static PWA
  command = "echo 'Static PWA - no build step required'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Security headers - MUST be first to avoid conflicts
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://source.unsplash.com https://images.unsplash.com https://unsplash.com https://*.unsplash.com https://upload.wikimedia.org https://*.wikimedia.org; connect-src 'self' https://api.unsplash.com https://en.wikipedia.org https://source.unsplash.com https://*.wikipedia.org https://*.wikimedia.org https://api.wikimedia.org; font-src 'self'; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"

# Headers for PWA files
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirects (for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling (if needed in future)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
